url: "https://monnem.sotaro.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "monnem.sotaro.io" # the name of your site, e.g. ACME Corp.
